
version: "3.8"

services:
  mysql:
    image: mysql
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "135791"
    volumes:
      - /Users/tmota/devel/teach/__25FCSC3022_CCCS/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$${MYSQL_ROOT_PASSWORD} || exit 1"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 80s

  salesapp:
    build: .
    image: salesapp
    container_name: salesapp
    expose: 
      - "5000"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SECRET_KEY: "change-me-in-prod"
  waf:
      image: owasp/modsecurity-crs:nginx
      container_name: waf
      restart: unless-stopped
      ports:
        - "8080:8080"              # Public entrypoint for your app via WAF
      environment:
        # Reverse proxy target (internal service + port)
        BACKEND: http://salesapp:5000
      depends_on: 
        - salesapp
